name:                modbus
version:             0.1.0.0
github:              "Lupino/modbus"
license:             BSD3
author:              "Lupino"
maintainer:          "lmjubuntu@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lupino/modbus#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - binary
  - hex
  - bytestring
  - unordered-containers
  - stm
  - aeson
  - text

tests:
  modbus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modbus
